-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["runp"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -33, -59  ,  -43, -44  ,  -45, -48  ,  -45, -57  ,  -38, -65  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -20, 64  ,  -22, 62  ,  -15, 58  ,  -15, 63  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -13, 49  ,  -15, 58  ,  -22, 62  ,  -22, 49  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   25, 22  ,  25, 17  ,  27, 17  ,  28, 20  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -52, -38  ,  -52, -31  ,  -57, -37  ,  -57, -40  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   31, 42  ,  33, 44  ,  33, 58  ,  26, 48  ,  27, 42  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -40, -40  ,  -35, -28  ,  -48, -29  ,  -52, -31  ,  -52, -38  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   28, -14  ,  25, 3  ,  -16, -13  ,  -19, -16  ,  -19, -18  ,  24, -17  ,  28, -16  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   21, -54  ,  24, -19  ,  24, -17  ,  -43, -44  ,  -14, -57  ,  -3, -60  ,  14, -60  ,  19, -58  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   34, -39  ,  24, -19  ,  21, -54  ,  30, -51  ,  34, -46  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   25, 3  ,  28, -14  ,  30, -13  ,  31, -5  ,  29, 1  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -40, -23  ,  -37, -17  ,  -47, -19  ,  -47, -21  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -35, -28  ,  -27, -19  ,  -37, -17  ,  -40, -23  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -35, -28  ,  -40, -40  ,  -40, -42  ,  24, -17  ,  -19, -18  ,  -27, -19  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -15, 58  ,  -13, 49  ,  26, 48  ,  33, 58  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -29, -57  ,  -43, -44  ,  -33, -59  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -14, -57  ,  -43, -44  ,  -29, -57  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   23, 47  ,  -15, -3  ,  -16, -13  ,  25, 22  ,  26, 36  ,  25, 45  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -15, 46  ,  23, 47  ,  26, 48  ,  -13, 49  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -15, -3  ,  23, 47  ,  -15, 46  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -16, -13  ,  25, 3  ,  25, 22  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   24, -17  ,  -40, -42  ,  -43, -44  }
                    }
                    
                    
                    
		}
		
		, 
		["clock"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 4, friction = 6.2, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   40, 96.5  ,  -55, 81.5  ,  -57, 79.5  ,  34, -15.5  ,  38, -14.5  ,  57, 80.5  ,  46, 93.5  ,  43, 96.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 4, friction = 6.2, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -54, 86.5  ,  -55, 81.5  ,  40, 96.5  ,  39, 98.5  ,  -39, 96.5  ,  -48, 93.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 4, friction = 6.2, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -40, -14.5  ,  -36, -15.5  ,  34, -15.5  ,  -57, 79.5  ,  -57, 3.5  ,  -51, -8.5  ,  -46, -12.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 4, friction = 6.2, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   48, -11.5  ,  54, -4.5  ,  57, 2.5  ,  57, 80.5  ,  38, -14.5  ,  42, -14.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 4, friction = 6.2, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   46, 93.5  ,  57, 80.5  ,  53, 88.5  ,  48, 93.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 4, friction = 6.2, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -36, -15.5  ,  -40, -14.5  ,  -40, -107.5  ,  -36, -107.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 4, friction = 6.2, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   38, -107.5  ,  38, -14.5  ,  34, -15.5  ,  34, -107.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 4, friction = 6.2, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -39, 96.5  ,  39, 98.5  ,  -39, 98.5  }
                    }
                    
                    
                    
		}
		
		, 
		["displays"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -82.5, 3.5  ,  73.5, 3.5  ,  73.5, 92.5  ,  -82.5, 92.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -62.5, -107.5  ,  -62.5, 3.5  ,  -66.5, 3.5  ,  -66.5, -107.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   57.5, -107.5  ,  57.5, 3.5  ,  53.5, 3.5  ,  53.5, -107.5  }
                    }
                    
                    
                    
		}
		
		, 
		["jumpers"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   58, -6  ,  57, -21  ,  62, -15  ,  64, -5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3, -21  ,  0, -26  ,  2, -26  ,  4, -24  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   48, -1  ,  44, -23  ,  53, -23  ,  57, -21  ,  58, -6  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   49, -35  ,  44, -40  ,  54, -40  ,  54, -37  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   46, -31  ,  33, -32  ,  40, -38  ,  44, -40  ,  49, -35  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   44, -23  ,  33, -32  ,  46, -31  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   29, -33  ,  19, -32  ,  28, -42  ,  32, -43  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   30, -27  ,  14, -17  ,  19, -32  ,  29, -33  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -59, -3  ,  -62, -9  ,  -63, -22  ,  -60, -24  ,  -55, -23  ,  -52, -2  ,  -56, -1  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -4, 39  ,  -12, 22  ,  16, 38  ,  14, 41  ,  10, 43  ,  3, 44  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -45, 11  ,  -47, 8  ,  -47, 1  ,  -37, 10  ,  -40, 12  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -34, -44  ,  -51, -4  ,  -52, -2  ,  -55, -23  ,  -54, -33  ,  -48, -41  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -37, 10  ,  -15, 21  ,  -26, 21  ,  -33, 17  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -51, -4  ,  8, -16  ,  14, -17  ,  39, 15  ,  -12, 22  ,  -15, 21  ,  -47, 1  ,  -51, -2  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   39, 15  ,  33, -30  ,  33, -32  ,  44, -23  ,  48, -1  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   16, 38  ,  -12, 22  ,  39, 15  ,  38, 20  ,  26, 36  ,  22, 38  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -10, -35  ,  0, -26  ,  3, -21  ,  -34, -44  ,  -21, -41  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -47, 1  ,  -15, 21  ,  -37, 10  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   8, -16  ,  -51, -4  ,  -34, -44  ,  3, -21  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   39, 15  ,  30, -27  ,  33, -30  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   39, 15  ,  14, -17  ,  30, -27  }
                    }
                    
                    
                    
		}
		
		, 
		["doug"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -49, 37  ,  -48, 38  ,  -49, 38  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -50, 36  ,  -49, 37  ,  -50, 37  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -52, 33  ,  -51, 34  ,  -52, 34  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -53, -24  ,  -54, -23  ,  -54, -24  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -51, -27  ,  -52, -26  ,  -52, -27  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -49, -30  ,  -50, -29  ,  -50, -30  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -48, -31  ,  -49, -30  ,  -49, -31  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -12, -35  ,  -13, -34  ,  -13, -35  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   8, -37  ,  -14, -32  ,  7, -38  ,  8, -38  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   13, -34  ,  12, -35  ,  13, -35  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   48, -30  ,  47, -31  ,  48, -31  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   50, -27  ,  49, -28  ,  50, -28  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   52, -24  ,  51, -25  ,  52, -25  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   51, 32  ,  52, 31  ,  52, 32  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   49, 35  ,  50, 34  ,  50, 35  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   48, 36  ,  49, 35  ,  49, 36  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -51, 34  ,  -50, 36  ,  -51, 36  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -53, 31  ,  -52, 33  ,  -53, 33  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -54, 29  ,  -53, 31  ,  -54, 31  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -55, 27  ,  -54, 29  ,  -55, 29  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -56, 25  ,  -48, -31  ,  -55, 27  ,  -56, 27  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -57, 23  ,  -56, 25  ,  -57, 25  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -58, -13  ,  -59, -11  ,  -59, -13  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -56, -18  ,  -57, -16  ,  -57, -18  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -54, -23  ,  -55, -21  ,  -55, -23  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -52, -26  ,  -53, -24  ,  -53, -26  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -50, -29  ,  -51, -27  ,  -51, -29  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -13, -34  ,  -14, -32  ,  -14, -34  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -10, -36  ,  -12, -35  ,  -12, -36  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   10, -36  ,  8, -37  ,  10, -37  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   12, -35  ,  10, -36  ,  12, -36  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   14, -32  ,  13, -34  ,  14, -34  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   49, -28  ,  48, -30  ,  49, -30  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   51, -25  ,  50, -27  ,  51, -27  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   53, -22  ,  52, -24  ,  53, -24  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   54, -20  ,  53, -22  ,  54, -22  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   55, -18  ,  54, -20  ,  55, -20  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   57, -13  ,  56, -15  ,  57, -15  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   55, 24  ,  56, 22  ,  56, 24  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   53, 29  ,  54, 27  ,  54, 29  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   52, 31  ,  53, 29  ,  53, 31  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   50, 34  ,  51, 32  ,  51, 34  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   47, 38  ,  -48, -31  ,  -48, -32  ,  -14, -32  ,  48, 36  ,  48, 38  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -58, 20  ,  -57, 23  ,  -58, 23  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -59, 17  ,  -51, -27  ,  -48, -31  ,  -58, 20  ,  -59, 20  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -61, -3  ,  -60, -7  ,  -58, -13  ,  -56, -18  ,  -53, -24  ,  -60, 13  ,  -61, 13  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -57, -16  ,  -58, -13  ,  -58, -16  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -55, -21  ,  -56, -18  ,  -56, -21  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -7, -37  ,  -10, -36  ,  -10, -37  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   56, -15  ,  55, -18  ,  56, -18  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   59, 13  ,  58, -9  ,  59, -9  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   60, 13  ,  59, 13  ,  59, -6  ,  60, -6  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   58, 16  ,  51, -25  ,  58, -9  ,  59, 13  ,  59, 16  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   57, 19  ,  51, -25  ,  58, 16  ,  58, 19  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   56, 22  ,  57, 19  ,  57, 22  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   54, 27  ,  55, 24  ,  55, 27  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   64, 10  ,  60, 10  ,  60, -3  ,  64, -3  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -60, 13  ,  -53, -24  ,  -52, -26  ,  -51, -27  ,  -59, 17  ,  -60, 17  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -60, -7  ,  -61, -3  ,  -61, -7  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -59, -11  ,  -60, -7  ,  -60, -11  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   58, -9  ,  57, -13  ,  58, -13  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -64, -3  ,  -61, -3  ,  -61, 10  ,  -64, 10  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   7, -39  ,  -7, -37  ,  -7, -39  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -51, 34  ,  -48, 38  ,  -50, 36  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -54, 29  ,  -51, 34  ,  -52, 33  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -53, -24  ,  -56, -18  ,  -55, -21  ,  -54, -23  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -48, -31  ,  -51, -27  ,  -50, -29  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -12, -35  ,  -10, -36  ,  -7, -37  ,  7, -39  ,  7, -38  ,  -14, -32  ,  -13, -34  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   13, -34  ,  48, 36  ,  -14, -32  ,  8, -37  ,  12, -35  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   49, -28  ,  48, 36  ,  14, -32  ,  47, -31  ,  48, -30  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   51, -25  ,  57, 19  ,  48, 36  ,  49, -28  ,  50, -27  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   55, -18  ,  58, -9  ,  51, -25  ,  52, -24  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   51, 32  ,  55, 24  ,  54, 27  ,  52, 31  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   48, 36  ,  57, 19  ,  56, 22  ,  50, 34  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -58, -13  ,  -60, -7  ,  -59, -11  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   58, -9  ,  56, -15  ,  57, -13  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -58, 20  ,  -48, -31  ,  -56, 25  ,  -57, 23  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -56, -18  ,  -58, -13  ,  -57, -16  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -54, 29  ,  -55, 27  ,  -48, -31  ,  47, 38  ,  47, 39  ,  -48, 38  ,  -51, 34  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   47, -31  ,  14, -32  ,  47, -32  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 100, friction = 100, bounce = 10, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -48, 38  ,  47, 39  ,  -48, 39  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

